name: sparkvibe-app
services:
  # Backend service
  - name: backend
    source_dir: /backend
    github:
      repo: reehan7086/SparkVibe
      branch: main
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
    routes:
      - path: /
    health_check:
      http_path: /health

  # Frontend service  
  - name: frontend
    source_dir: /frontend
    github:
      repo: reehan7086/SparkVibe
      branch: main
    build_command: node --version && npm --version && npm ci && npm run build
    run_command: npx serve -s dist -l 8080
    environment_slug: node-js
    instance_count: 1 
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.11.0"
      - key: NPM_VERSION  
        value: "10.2.4"
      - key: VITE_API_URL
        value: https://backend-sv-3n4v6.ondigitalocean.app
    routes:
      - path: /
    health_check:
      http_path: /

domains:
  - domain: sparkvibe.app
    type: PRIMARY
  - domain: www.sparkvibe.app
    type: ALIAS