name: sparkvibe-app
services:
  - name: frontend
    source_dir: /frontend
    github:
      repo: reehan7086/SparkVibe
      branch: main
    environment_slug: node-js
    run_command: cd frontend && npm run preview -- --host --port 8080
    build_command: cd frontend && npm install && npm run build
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
        domain: sparkvibe.app
    health_check:
      http_path: /
      port: 8080
      initial_delay_seconds: 15
      period_seconds: 10
    envs:
      - key: VITE_API_URL
        value: https://api.sparkvibe.app
      - key: NODE_ENV
        value: production

  - name: backend
    source_dir: /backend
    github:
      repo: reehan7086/SparkVibe
      branch: main
    environment_slug: node-js
    run_command: cd backend && npm start
    build_command: cd backend && npm install
    http_port: 5000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
        domain: api.sparkvibe.app
    health_check:
      http_path: /api/health
      port: 5000
      initial_delay_seconds: 20
      period_seconds: 15
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"